name: blockchain
channels:
  - conda-forge
  - defaults
dependencies:
  - base58=2.1.1=pyhd8ed1ab_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cffi=2.0.0=py312h02ab6af_1
  - colorama=0.4.6=py312haa95532_0
  - cryptography=46.0.3=py312habbc9f9_0
  - expat=2.7.4=hd7fb8db_0
  - iniconfig=2.3.0=py312haa95532_0
  - jsonalias=0.1.1=pyhd8ed1ab_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - markdown-it-py=4.0.0=py312haa95532_1
  - mdurl=0.1.2=py312haa95532_0
  - mnemonic=0.21=pyhd8ed1ab_1
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py312haa95532_1
  - pathspec=0.12.1=py312haa95532_1
  - pbkdf2=1.3=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - pluggy=1.5.0=py312haa95532_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - pygments=2.19.2=py312haa95532_0
  - pytest=9.0.2=py312haa95532_0
  - python=3.12.12=h716150d_1
  - python_abi=3.12=3_cp312
  - questionary=2.1.1=pyhd8ed1ab_0
  - rich=14.2.0=py312haa95532_0
  - setuptools=80.10.2=py312haa95532_0
  - solders=0.27.1=py312hb0142fd_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.46.3=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - cbor2==5.8.0
      - coincurve==21.0.0
      - crcmod==1.7
      - dotenv==0.9.9
      - ecdsa==0.19.1
      - ed25519-blake2b==1.4.1
      - py-sr25519-bindings==0.2.3
      - pycparser==3.0
      - pycryptodome==3.23.0
      - pynacl==1.6.2
      - python-dotenv==1.2.1
      - six==1.17.0
prefix: C:\Users\Asus\anaconda3\envs\blockchain
